export type StateCities = { state: string; cities: string[] };

export const LOCATIONS: Record<string, StateCities[]> = {
  Pakistan: [
    { state: "Punjab", cities: ["Lahore", "Faisalabad", "Rawalpindi", "Multan", "Gujranwala", "Sialkot", "Bahawalpur", "Sargodha", "Sheikhupura"] },
    { state: "Sindh", cities: ["Karachi", "Hyderabad", "Sukkur", "Larkana", "Mirpur Khas", "Nawabshah"] },
    { state: "Khyber Pakhtunkhwa", cities: ["Peshawar", "Mardan", "Abbottabad", "Mingora", "Kohat", "Swat", "Nowshera"] },
    { state: "Balochistan", cities: ["Quetta", "Gwadar", "Turbat", "Khuzdar", "Chaman"] },
    { state: "Islamabad Capital Territory", cities: ["Islamabad"] },
    { state: "Azad Kashmir", cities: ["Muzaffarabad", "Mirpur", "Rawalakot"] },
    { state: "Gilgit-Baltistan", cities: ["Gilgit", "Skardu", "Hunza"] },
  ],
  "United States": [
    { state: "California", cities: ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Fresno"] },
    { state: "New York", cities: ["New York City", "Buffalo", "Rochester", "Albany", "Syracuse"] },
    { state: "Texas", cities: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso"] },
    { state: "Florida", cities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"] },
    { state: "Illinois", cities: ["Chicago", "Aurora", "Naperville", "Springfield"] },
    { state: "Pennsylvania", cities: ["Philadelphia", "Pittsburgh", "Allentown"] },
    { state: "Ohio", cities: ["Columbus", "Cleveland", "Cincinnati"] },
    { state: "Georgia", cities: ["Atlanta", "Savannah", "Augusta"] },
    { state: "North Carolina", cities: ["Charlotte", "Raleigh", "Greensboro"] },
    { state: "Michigan", cities: ["Detroit", "Grand Rapids", "Ann Arbor"] },
    { state: "New Jersey", cities: ["Newark", "Jersey City", "Paterson"] },
    { state: "Virginia", cities: ["Richmond", "Virginia Beach", "Arlington"] },
    { state: "Washington", cities: ["Seattle", "Spokane", "Tacoma", "Bellevue"] },
    { state: "Massachusetts", cities: ["Boston", "Worcester", "Cambridge"] },
    { state: "Arizona", cities: ["Phoenix", "Tucson", "Mesa", "Scottsdale"] },
  ],
  "United Kingdom": [
    { state: "England", cities: ["London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Bristol", "Sheffield", "Newcastle", "Leicester", "Nottingham"] },
    { state: "Scotland", cities: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness"] },
    { state: "Wales", cities: ["Cardiff", "Swansea", "Newport"] },
    { state: "Northern Ireland", cities: ["Belfast", "Derry", "Lisburn"] },
  ],
  "United Arab Emirates": [
    { state: "Abu Dhabi", cities: ["Abu Dhabi", "Al Ain"] },
    { state: "Dubai", cities: ["Dubai", "Jebel Ali"] },
    { state: "Sharjah", cities: ["Sharjah", "Khor Fakkan"] },
    { state: "Ajman", cities: ["Ajman"] },
    { state: "Fujairah", cities: ["Fujairah"] },
    { state: "Ras Al Khaimah", cities: ["Ras Al Khaimah"] },
    { state: "Umm Al Quwain", cities: ["Umm Al Quwain"] },
  ],
  "Saudi Arabia": [
    { state: "Riyadh", cities: ["Riyadh", "Diriyah", "Al Kharj"] },
    { state: "Makkah", cities: ["Makkah", "Jeddah", "Taif"] },
    { state: "Eastern Province", cities: ["Dammam", "Al Khobar", "Dhahran", "Jubail"] },
    { state: "Madinah", cities: ["Madinah", "Yanbu"] },
    { state: "Asir", cities: ["Abha", "Khamis Mushait"] },
    { state: "Qassim", cities: ["Buraydah", "Unaizah"] },
    { state: "Tabuk", cities: ["Tabuk"] },
    { state: "Hail", cities: ["Hail"] },
  ],
  Canada: [
    { state: "Ontario", cities: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London"] },
    { state: "Quebec", cities: ["Montreal", "Quebec City", "Laval", "Gatineau"] },
    { state: "British Columbia", cities: ["Vancouver", "Victoria", "Surrey", "Burnaby"] },
    { state: "Alberta", cities: ["Calgary", "Edmonton", "Red Deer"] },
    { state: "Manitoba", cities: ["Winnipeg", "Brandon"] },
    { state: "Saskatchewan", cities: ["Saskatoon", "Regina"] },
    { state: "Nova Scotia", cities: ["Halifax", "Dartmouth"] },
    { state: "New Brunswick", cities: ["Fredericton", "Moncton", "Saint John"] },
  ],
  Australia: [
    { state: "New South Wales", cities: ["Sydney", "Newcastle", "Wollongong"] },
    { state: "Victoria", cities: ["Melbourne", "Geelong", "Ballarat"] },
    { state: "Queensland", cities: ["Brisbane", "Gold Coast", "Cairns", "Townsville"] },
    { state: "Western Australia", cities: ["Perth", "Fremantle"] },
    { state: "South Australia", cities: ["Adelaide"] },
    { state: "Tasmania", cities: ["Hobart", "Launceston"] },
    { state: "Australian Capital Territory", cities: ["Canberra"] },
    { state: "Northern Territory", cities: ["Darwin", "Alice Springs"] },
  ],
  Germany: [
    { state: "Bavaria", cities: ["Munich", "Nuremberg", "Augsburg"] },
    { state: "Berlin", cities: ["Berlin"] },
    { state: "North Rhine-Westphalia", cities: ["Cologne", "Düsseldorf", "Dortmund", "Essen"] },
    { state: "Hamburg", cities: ["Hamburg"] },
    { state: "Hesse", cities: ["Frankfurt", "Wiesbaden"] },
    { state: "Baden-Württemberg", cities: ["Stuttgart", "Karlsruhe", "Mannheim"] },
    { state: "Saxony", cities: ["Dresden", "Leipzig"] },
  ],
  France: [
    { state: "Île-de-France", cities: ["Paris", "Versailles", "Boulogne-Billancourt"] },
    { state: "Provence-Alpes-Côte d'Azur", cities: ["Marseille", "Nice", "Toulon"] },
    { state: "Auvergne-Rhône-Alpes", cities: ["Lyon", "Grenoble", "Saint-Étienne"] },
    { state: "Occitanie", cities: ["Toulouse", "Montpellier"] },
    { state: "Nouvelle-Aquitaine", cities: ["Bordeaux", "Limoges"] },
    { state: "Hauts-de-France", cities: ["Lille", "Amiens"] },
    { state: "Bretagne", cities: ["Rennes", "Brest"] },
  ],
  India: [
    { state: "Maharashtra", cities: ["Mumbai", "Pune", "Nagpur", "Nashik"] },
    { state: "Delhi", cities: ["New Delhi", "Delhi"] },
    { state: "Karnataka", cities: ["Bengaluru", "Mysuru", "Mangaluru"] },
    { state: "Tamil Nadu", cities: ["Chennai", "Coimbatore", "Madurai"] },
    { state: "Telangana", cities: ["Hyderabad", "Warangal"] },
    { state: "Gujarat", cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot"] },
    { state: "West Bengal", cities: ["Kolkata", "Howrah"] },
    { state: "Punjab", cities: ["Amritsar", "Ludhiana", "Jalandhar", "Chandigarh"] },
    { state: "Rajasthan", cities: ["Jaipur", "Udaipur", "Jodhpur"] },
    { state: "Uttar Pradesh", cities: ["Lucknow", "Kanpur", "Agra", "Varanasi", "Noida"] },
    { state: "Kerala", cities: ["Kochi", "Thiruvananthapuram", "Kozhikode"] },
    { state: "Haryana", cities: ["Gurugram", "Faridabad"] },
  ],
  Bangladesh: [
    { state: "Dhaka", cities: ["Dhaka", "Gazipur", "Narayanganj"] },
    { state: "Chittagong", cities: ["Chittagong", "Comilla", "Cox's Bazar"] },
    { state: "Khulna", cities: ["Khulna", "Jessore"] },
    { state: "Rajshahi", cities: ["Rajshahi", "Bogra"] },
    { state: "Sylhet", cities: ["Sylhet"] },
    { state: "Barisal", cities: ["Barisal"] },
    { state: "Rangpur", cities: ["Rangpur", "Dinajpur"] },
    { state: "Mymensingh", cities: ["Mymensingh"] },
  ],
  Kuwait: [
    { state: "Al Asimah", cities: ["Kuwait City"] },
    { state: "Hawalli", cities: ["Hawalli", "Salmiya"] },
    { state: "Farwaniya", cities: ["Farwaniya"] },
    { state: "Mubarak Al-Kabeer", cities: ["Mubarak Al-Kabeer"] },
    { state: "Ahmadi", cities: ["Ahmadi", "Fahaheel"] },
    { state: "Jahra", cities: ["Jahra"] },
  ],
  Qatar: [
    { state: "Ad-Dawhah", cities: ["Doha"] },
    { state: "Al Rayyan", cities: ["Al Rayyan"] },
    { state: "Al Wakrah", cities: ["Al Wakrah"] },
    { state: "Al Khor", cities: ["Al Khor"] },
    { state: "Umm Salal", cities: ["Umm Salal"] },
  ],
  Bahrain: [
    { state: "Capital", cities: ["Manama"] },
    { state: "Muharraq", cities: ["Muharraq"] },
    { state: "Northern", cities: ["Budaiya", "Hamad Town"] },
    { state: "Southern", cities: ["Riffa", "Isa Town"] },
  ],
  Oman: [
    { state: "Muscat", cities: ["Muscat", "Seeb", "Bawshar"] },
    { state: "Dhofar", cities: ["Salalah"] },
    { state: "Al Batinah North", cities: ["Sohar"] },
    { state: "Al Batinah South", cities: ["Rustaq"] },
    { state: "Ad Dakhiliyah", cities: ["Nizwa"] },
    { state: "Ash Sharqiyah North", cities: ["Ibra"] },
    { state: "Ash Sharqiyah South", cities: ["Sur"] },
    { state: "Ad Dhahirah", cities: ["Ibri"] },
    { state: "Al Buraimi", cities: ["Al Buraimi"] },
    { state: "Musandam", cities: ["Khasab"] },
    { state: "Al Wusta", cities: ["Haima"] },
  ],
  Singapore: [
    { state: "Central Region", cities: ["Singapore"] },
    { state: "East Region", cities: ["Bedok", "Tampines", "Pasir Ris"] },
    { state: "North Region", cities: ["Woodlands", "Yishun"] },
    { state: "North-East Region", cities: ["Hougang", "Sengkang", "Punggol"] },
    { state: "West Region", cities: ["Jurong", "Bukit Batok", "Choa Chu Kang"] },
  ],
  Malaysia: [
    { state: "Kuala Lumpur", cities: ["Kuala Lumpur"] },
    { state: "Selangor", cities: ["Shah Alam", "Petaling Jaya", "Subang Jaya", "Klang"] },
    { state: "Johor", cities: ["Johor Bahru", "Iskandar Puteri"] },
    { state: "Penang", cities: ["George Town", "Butterworth"] },
    { state: "Perak", cities: ["Ipoh", "Taiping"] },
    { state: "Sabah", cities: ["Kota Kinabalu", "Sandakan"] },
    { state: "Sarawak", cities: ["Kuching", "Miri"] },
    { state: "Pahang", cities: ["Kuantan"] },
    { state: "Kedah", cities: ["Alor Setar"] },
    { state: "Negeri Sembilan", cities: ["Seremban"] },
    { state: "Melaka", cities: ["Malacca City"] },
    { state: "Terengganu", cities: ["Kuala Terengganu"] },
    { state: "Kelantan", cities: ["Kota Bharu"] },
  ],
};

export function getStatesForCountry(country: string): string[] {
  return (LOCATIONS[country] || []).map((s) => s.state);
}

export function getCitiesForState(country: string, state: string): string[] {
  return (LOCATIONS[country] || []).find((s) => s.state === state)?.cities || [];
}
